Moex\CoreBundle\Entity\MePostmeta:
  type: entity
  table: me_postmeta
  fields:
    metaId:
      id: true
      type: bigint
      nullable: false
      column: meta_id
      generator:
        strategy: IDENTITY
    postId:
      type: bigint
      nullable: false
      column: post_id
    metaKey:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: meta_key
    metaValue:
      type: text
      nullable: true
      column: meta_value
  lifecycleCallbacks: {  }
